### ISSUE TITLE
Showon doesn't work in subforms with multiple rows

### ISSUE THREAD

**Issue by crystalenka** [nikosdion/plg_content_fieldsshowon#1]
But it works beautifully in subforms that are not repeatable, so at least that. :)

I tried to figure out the problem but could not so I thought I'd file an issue.

Thank you for your help

**Comment by nikosdion** [comment]
Subforms always have multiple rows and I've definitely used it in a subform that had six rows.

You are trying to say something else but I can't guess what you mean.

**Comment by crystalenka** [comment]
Whoops, looks like it's not working in the inception field types--my mistake. Subforms do appear to work.

**Comment by nikosdion** [comment]
Yes, it cannot work on inception (subform-in-subform) fields. Joomla's showon code is strictly single-level. Each inception level makes it impossible to reference fields outside of it, or you'd have some really nasty artefacts making it impossible to use showon. Sorry.

**Comment by crystalenka** [comment]
I know it can't work ON inception fields, but I thought it might work within the first level? Maybe i misunderstood. No problem either way. Thank you

**Comment by nikosdion** [comment]
You can have a custom field (e.g. a list field) control whether a subform field will show up. This is only possible when both the control field and the subform field are NOT contained in a subform or inception field.

You can have `showon` in the fields contained in a subform row regardless of whether it is repeatable or not, as long as both the control field and the controlled field (which has the showon rule) are inside the same subform.

You can **NOT** have `showon` in the fields contained in an inception (nested subforms) field at all. This is NOT a glorified subform field. We have to abuse and corrupt Joomla's custom field handling to do things many would say are… unnatural.
