### ISSUE TITLE
using "[OR]" causes PHP warning

### ISSUE THREAD

**Issue by crystalenka** [nikosdion/plg_content_fieldsshowon#2]
When you use `[OR]` in a shown condition, a PHP warning is shown, and shown functionality does not work:

```
Warning: Undefined array key 1 in /plugins/content/fieldsshowon/src/Extension/FieldsShowOn.php on line 589
```

I tried to figure out what was wrong but couldn't decipher the code in this part.

**Comment by nikosdion** [comment]
You get a warning because you have invalid syntax in your `showon` expression. It looks like you have an `[OR]` or `[AND]` which is not followed by a field condition.
