### ISSUE TITLE
 Failed to set up the "Show On" field !

### ISSUE THREAD

**Issue by HDInfautre** [nikosdion/plg_content_fieldsshowon#3]
Hello
Thank you for this plugin which has a very important feature for me, if I understood correctly it allows on a form to show/hide a field according to another custom field?

Nevertheless, I didn't understand the syntax to use. I see a "Show On" field. When I hover over it, there is a link in blue that I don't read: and if I go to : https://github.com/nikosdion/plg_content_fieldsshowon#readme, I don't get an explanation either.

Can you tell me where to find this syntax?

**Comment by woluweb** [comment]
If you install the plugin, you have a new Parameter when you edit any Custom Field, called "Show On".
There is a line of explanation below that Parameter:
`Controls when the custom field will be shown based on the values of one or more custom fields. Use the Show On notation explained in the [Joomla! documentation](https://docs.joomla.org/Form_field#Showon).`

Follow that link and you will have examples. It works "the standard Joomla way".

Let's take an example from my site:
- I have another Custom Field of Type List, called "blabla" and having 2 possible values : "open" or "closed"
- then I would type the following to show my Custom Field only if blabla is set on open :
`blabla:open`

**Comment by HDInfautre** [comment]
Thanks
